build fips helper images

diff --git a/ci/package b/ci/package
--- a/ci/package
+++ b/ci/package
@@ -86,6 +86,66 @@ create_package() {
         "${base_input_part}ubuntu-x86_64.tar.xz=${base_output_part}ubuntu-x86_64.tar.xz"
 }
 
+create_package_fips() {
+    local packageType=${1}
+    shift
+
+    local customOptions
+    read -r -a customOptions <<< "${@}"
+
+    if [ -z "${PACKAGE_ARCH}" ]; then
+      echo "PACKAGE_ARCH not specified, aborting."
+      exit 1
+    fi
+
+    local uname_s
+    uname_s=$(uname -s)
+
+    if [[ "${uname_s}" == "Darwin" ]]; then
+        check_macos_package "gtar" "gnu-tar"
+        check_macos_package "rpmbuild" "rpm"
+    fi
+
+    mkdir -p "out/${packageType}/"
+
+    local base_input_part="out/helper-images/prebuilt-"
+    local base_output_part="/usr/lib/gitlab-runner/helper-images/prebuilt-"
+
+    fpm \
+        --package "out/${packageType}/${PACKAGE_NAME}_${PACKAGE_ARCH}.${packageType}" \
+        --force \
+        --input-type dir \
+        --output-type "${packageType}" \
+        \
+        --name "${PACKAGE_NAME}" \
+        --description "GitLab Runner" \
+        --version "${VERSION}" \
+        --url https://gitlab.com/gitlab-org/gitlab-runner \
+        --maintainer "GitLab Inc. <support@gitlab.com>" \
+        --license "MIT" \
+        --vendor "GitLab Inc." \
+        --architecture "${PACKAGE_ARCH}" \
+        \
+        --conflicts "${PACKAGE_NAME}-beta" \
+        --conflicts gitlab-ci-multi-runner \
+        --conflicts gitlab-ci-multi-runner-beta \
+        --provides gitlab-ci-multi-runner \
+        --replaces gitlab-ci-multi-runner \
+        \
+        --depends git \
+        --depends curl \
+        --depends tar \
+        \
+        "${customOptions[@]}" \
+        \
+        --after-install "packaging/scripts/postinst.${packageType}" \
+        --before-remove "packaging/scripts/prerm.${packageType}" \
+        \
+        packaging/root/=/ \
+        "${RUNNER_BINARY}=/usr/bin/gitlab-runner" \
+        "${base_input_part}redhat-x86_64-fips.tar.xz=${base_output_part}redhat-fips-x86_64.tar.xz" # TODO ORDERING
+}
+
 create_deb() {
     local options=()
     options+=("--depends ca-certificates")
